INSERT INTO reviews (user_id, beer_id, review, sweet, sour, hoppy, bitter, rank)
VALUES
(1,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',3,4,3,5,4),
(1,4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',4,3,2,2,5),
(1,6,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',1,2,4,5,3),
(1,8,'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',5,5,1,4,4),
(1,12,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in risus vehicula mauris non.',5,2,3,1,4),
(2,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec cursus ipsum. ur tellus.',3,4,3,5,4),
(2,3,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec cursus ipsum. ur tellus.',1,2,3,5,4),
(2,4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec cursus ipsum. ur tellus.',4,3,2,2,5),
(2,8,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec cursus ipsum. ur tellus.',5,5,1,4,4),
(2,12,'Lorem ipsum dolor sit amet, consectit. Suspendisse rhoncus sit amet orci ultrices ultricies.',5,2,3,1,4),
(3,2,'Lorem ipsum dolor sit amet adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,1,1,3,4),
(3,6,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,3,5,5,4),
(3,8,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',2,2,7,4,5),
(3,12,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',7,5,2,4,5),
(3,14,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',4,2,8,5,3),
(4,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',3,1,3,5,4),
(4,3,'Lorem ipsum dolor sit amet adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,5,4,4,3),
(4,6,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,4,4,2,5),
(4,7,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,2,3,1,4),
(4,10,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',5,5,4,1,3),
(4,14,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,4,4,1,2),
(5,2,'Lorem ipsum dolor sit amet adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,1,1,3,1),
(5,6,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,4,2,1),
(5,10,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,4,2,2),
(5,12,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,4,2,3),
(5,14,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,4,2,5),
(6,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',3,4,1,1,4),
(6,4,'Lorem ipsum dolor sit amet adipiscing elit. In blandit porttitor eros, sit amet luctus.',5,4,4,3,5),
(6,10,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,4,2,4),
(6,12,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',4,3,4,2,4),
(6,16,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,3,2,2,4),
(6,18,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,5,4,4,5),
(7,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',4,4,4,5,4),
(7,3,'Lorem ipsum dolor sit amet adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,5,4,4,5),
(7,6,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,4,2,3),
(7,14,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,5,4,2,3),
(7,16,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,3,5,2,3),
(8,3,'Lorem ipsum dolor sit amet adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,1,1,3,4),
(8,6,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,3,4,2,4),
(8,10,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',4,3,4,2,5),
(9,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc odio ut enim quis.',3,4,3,5,4),
(9,4,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',1,5,4,4,5),
(9,10,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,1,4,2,2),
(9,12,'Lorem ipsum dolor si, consectetur adipiscing elit. In blandit porttitor eros, sit amet luctus.',3,4,4,2,2);